### ISSUE TITLE
building with MSYS2

### ISSUE THREAD

**Issue by easyw** [alyoshin/gerbv-dxf#1]
Hi,
I'm trying to build it in MSYS2 mingw64 (gcc.exe (Rev2, Built by MSYS2 project) 5.3.0)...
I've done:
1) unzipped https://github.com/alyoshin/gerbv-dxf/archive/master.zip to ~/gerbv-dxf-master
2) installed gtk+ with "pacman -S mingw-w64-i686-gtk3"
3) installed autoconf, automake with "pacman -S autoconf" and "pacman -S automake"
 (autoconf (GNU Autoconf) 2.69, automake (GNU automake) 1.15)
4) run "./configure"
but I get this error
./configure: line 2397: `AM_INIT_AUTOMAKE(1.9)' syntax error near unexpected token `1.9'
am I missing something?
thanx
Maurice

**Comment by easyw** [comment]
ok, I solved like that:
```
cd gerbv-dxf-master
pacman -Ss gtk2
pacman -S mingw-w64-i686-gtk2
pacman -S autoreconf
pacman -S autoconf
pacman -S libtool
autoreconf -fi
./configure --enable-unit-mm --enable-dxf
make
make install
```
what I missed then it was dxflib-master
now everything is working
just a suggestion:
why not using libdxfrw-0.6.3?
they are free for all use
Thanks :+1:

**Comment by alyoshin** [comment]
Hello, easyw

 > why not using libdxfrw-0.6.3?

The only reason for using libdxf -- it is in Debian repository.

**Comment by easyw** [comment]
Hi alyoshin,

**Comment by easyw** [comment]
Hi alyoshin, I think your code should be merged with official gerbv :) 
Thanx for your code...
